import type { ConflictResolution } from "../calendar/types";

export const COPY = {
  scheduleOnTimeline: "Schedule on timeline",
  moveBlock: "Move block",
  resize: "Resize",
  resizeStart: "Resize start",
  resizeEnd: "Resize end",
  unschedule: "Unschedule",
  reorderInChain: "Reorder in chain",
  moveToChain: "Move to chain",
  moveEarlier: "Move earlier",
  moveLater: "Move later",
  makeFixed: "Make Fixed",
  makeFlexible: "Make Flexible",
  markAsRunning: "Mark as running",
  clearRunning: "Clear running",
  openTaskBoard: "Open Task Board",
  createReserve: "Create reserve",
  addReserve: "Add reserve",
  applyPreview: "Apply preview",
  cancel: "Cancel",
  retry: "Retry",
  reserve: "Reserve",
  unscheduled: "Unscheduled",
  emptyStep: "Drag a task onto the timeline, or plan tomorrow.",
  errorUnchanged: "The schedule in force is unchanged.",
  offline: "Offline",
  savedLocally: "Saved on this device",
  savePending: "Save pending",
  fiveMinutes: "Five minutes left on this block.",
  keepAnyway: "Keep Anyway",
  changeDuration: "Change duration",
  changeOrder: "Change order",
  movePastAnchor: "Move past the anchor",
  unscheduleBlock: "Unschedule block",
  dropUnschedule: "Drop here to unschedule",
  overloaded: "This day is overloaded.",
  dayClosePending: "The previous day is still open.",
  previewTitle: "Confirm change",
  affectedChains: "Affected chains",
  resultingTimes: "Resulting times",
  chooseType: "Choose a block type. Type is never taken from the drop.",
  fixed: "Fixed",
  flexible: "Flexible",
  duration: "Duration (minutes)",
  startTime: "Start time",
  chainPosition: "Chain position",
  conflict: "Conflict",
  chainFromStart: "Chain from the start of the day",
  partialFailure: "This block could not be saved.",
} as const;

export const CONFLICT_RESOLUTION_COPY: Record<ConflictResolution, string> = {
  changeDuration: COPY.changeDuration,
  changeOrder: COPY.changeOrder,
  moveBlockPastAnchor: COPY.movePastAnchor,
  unscheduleBlock: COPY.unscheduleBlock,
  keepConflict: COPY.keepAnyway,
};
