export const COPY = {
  now: "Now",
  nothingRunning: "Nothing running.",
  prepareHint: "Choose a task, then Start. Nothing is recorded until Start.",
  task: "Task",
  block: "Calendar block",
  unscheduled: "Unscheduled",
  start: "Start",
  pause: "Pause",
  resume: "Resume",
  switchTask: "Switch task",
  stopEarly: "Stopped early",
  discard: "Discarded",
  continueCycle: "Continue",
  defaultDuration: "Default duration (minutes)",
  remaining: "Remaining",
  budget: "Budget",
  awaitingReconciliation: "Awaiting reconciliation",
  lastCertain: "Last certain moment",
  countFocus: "Count the gap as focus",
  countPause: "Count the gap as a pause",
  confirmInterrupt: "Confirm the interruption",
  unreconciled: "This cycle is not a completed Pomodoro until you reconcile.",
  offerBreak: "Take a 5-minute break?",
  startBreak: "Start break",
  skipBreak: "Skip break",
  breakRunning: "Break",
  existingCycle: "A Pomodoro is already in progress.",
  soundOptIn: "Play sound",
  previewSound: "Preview sound",
  alertsOptIn: "Allow alerts",
  mutedNote: "Events stay readable while muted.",
  skipFlourish: "Skip animation",
  timerComplete: "Timer complete",
  fiveMinutes: "Five minutes left on this block.",
  emptyStep: "Pick a live task to prepare a Pomodoro.",
  loading: "Loading timer",
  saveError: "Could not save the cycle.",
  focusSafe: "Confirmed focus time already stored is kept.",
  retry: "Retry",
  offline: "Offline",
  savedLocally: "Saved on this device",
  savePending: "Save pending",
} as const;
