export const COPY = {
  title: "Reports",
  workingTime: "Working time",
  taskOutcomes: "Task outcomes",
  contribution: "Contribution",
  timeByTask: "Time by Task",
  period: "Period",
  previous: "Previous period",
  next: "Next period",
  contributionYear: "Contribution year",
  previousYear: "Previous year",
  nextYear: "Next year",
  empty: "No data yet for the selected period.",
  loading: "Loading reports",
  offline: "Offline",
  savedLocally: "History is stored on this device",
  retry: "Retry",
  errorKept: "Recorded history is still here.",
  countNote: "These are task-status counts, not a unique task count.",
  discardedTrace: "Discarded cycles (not in totals)",
  legend: "Contribution levels",
  share: "Share",
  identify: "Task",
  dayGroup: "Workie day",
  noPrimary: "Reports is a reading surface.",
} as const;
