/** English UI copy for the Task Board. Canonical status names stay un-reworded [D78] [D86]. */
export const COPY = {
  boardTitle: "Task Board",
  createTask: "Create task",
  close: "Close",
  complete: "Complete",
  restore: "Restore",
  moreActions: "More actions",
  abandon: "Abandon",
  cancel: "Cancel",
  confirmAbandon: "Confirm Abandon",
  confirmCancel: "Confirm Cancel",
  goBack: "Go back",
  abandonConfirm: "Abandon this task? It will move to Abandoned.",
  cancelConfirm: "Cancel this task? It will move to Cancelled.",
  addToDayPlan: "Add to day plan",
  moveUp: "Move up",
  moveDown: "Move down",
  moveToWaiting: "Move to Waiting",
  moveToInProgress: "Move to In Progress",
  moveToDeferred: "Move to Deferred",
  openTask: "Open task",
  closeDetail: "Close task",
  emptyStep: "Create a task to start.",
  unscheduled: "Unscheduled",
  scheduled: "Scheduled",
  repeat: "Repeat",
  title: "Title",
  description: "Description",
  subtasks: "Subtasks",
  addSubtask: "Add subtask",
  removeSubtask: "Remove subtask",
  sourceCreator: "Source / creator",
  currentAccount: "current account",
  formCancel: "Cancel",
  offline: "Offline",
  saveStateOnline: "Saved on this device",
  saveStateOffline: "Edits stay on this device",
  notChanged: "The task was not changed.",
  retry: "Retry",
  loading: "Loading tasks",
  skipFlourish: "Skip animation",
  weekdayGroup: "Weekdays",
  titleRequired: "Title is required.",
  weekdayRequired: "Choose at least one weekday.",
  blocksHeading: "Blocks",
  focusHeading: "Focus sessions",
  recurrenceHeading: "Recurrence",
  sourceHeading: "Source",
  historyHeading: "Status history",
  noBlocks: "No blocks",
  noFocus: "No focus sessions",
  oneOff: "One-off",
  daily: "Daily",
} as const;

export const WEEKDAY_OPTIONS = [
  { label: "Mon", value: 1 as const },
  { label: "Tue", value: 2 as const },
  { label: "Wed", value: 3 as const },
  { label: "Thu", value: 4 as const },
  { label: "Fri", value: 5 as const },
  { label: "Sat", value: 6 as const },
  { label: "Sun", value: 0 as const },
] as const;
