/** English import copy. Canonical duplicate strings stay un-reworded [D15] [D78]. */
export const COPY = {
  importBatch: "Import batch",
  dropHint: "Select or drop workie-batch.v1.json to start an import.",
  reviewTitle: "Review import",
  claudeCowork: "Claude Cowork",
  sourceName: "Source name",
  sourceMark: "Source mark",
  itemKey: "Item key",
  title: "Title",
  description: "Description",
  subtasks: "Subtasks",
  addSubtask: "Add subtask",
  removeSubtask: "Remove subtask",
  selectTask: "Include in import",
  certainDuplicate: "Certain duplicate",
  possibleDuplicate: "Possible duplicate",
  newItem: "New",
  addAnyway: "Add anyway",
  compare: "Compare",
  existing: "Existing",
  incoming: "Incoming",
  moveUp: "Move up",
  moveDown: "Move down",
  confirm: "Confirm import",
  discard: "Discard import",
  discardPrompt: "Discard this import? The review draft will be removed.",
  keepReview: "Keep review",
  confirmDiscard: "Confirm discard",
  loading: "Checking the batch",
  offline: "Offline",
  saveStateOnline: "Saved on this device",
  saveStateOffline: "Edits stay on this device",
  commitRecovery: "Nothing was imported. Your review is kept.",
  expectedFilename: "Expected filename workie-batch.v1.json.",
} as const;
