export const COPY = {
  title: "Plan Tomorrow",
  stepSelect: "Select",
  stepPlace: "Place",
  stepReview: "Review",
  continuePlace: "Continue to place",
  continueReview: "Continue to review",
  commitTomorrow: "Commit Tomorrow",
  keepAnyway: "Keep Anyway",
  skipFlourish: "Skip animation",
  empty: "Create a task first, then return to Plan Tomorrow.",
  loading: "Loading the suggestion tray",
  draftError: "Could not save the draft.",
  draftKept: "Your draft content is still here.",
  retry: "Retry",
  offline: "Offline",
  savedLocally: "Draft saved on this device",
  savePending: "Save pending",
  notCommitment: "Selected, with no block — not a commitment.",
  addFixed: "Add fixed block",
  addFlexible: "Add flexible block",
  placeFixed: "Place fixed block",
  placeFlexible: "Place flexible block",
  duration: "Duration (minutes)",
  startHour: "Start hour",
  startMinute: "Start minute",
  chainPosition: "Chain position",
  precedingAnchor: "Chain after",
  dayStart: "Start of day",
  reviewClean: "No conflict or overload.",
  fixPlan: "Go back and fix",
  insertTitle: "Insert unplanned work",
  pickTask: "Existing task",
  newTask: "New task title",
  createAndInsert: "Create and preview",
  previewInsert: "Preview insertion",
  confirmInsert: "Confirm insertion",
  cancel: "Cancel",
  chooseType: "Block type",
  fixed: "Fixed",
  flexible: "Flexible",
  dayCloseTitle: "The day has closed.",
  dayCloseBody:
    "Unfinished tasks returned to the tray. Carry them to today? This is not a commitment.",
  carry: "Carry to tray",
  skipCarry: "Skip",
  whyPrefix: "Why",
  partialFailure: "This block could not be placed.",
} as const;
